version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vapor-composer-image
    volumes:
       - ./app:/app
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 8080:8080
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test